"""added subject-wise attendance

Revision ID: aea7ae9a6049
Revises: fcd3bdb2b30b
Create Date: 2026-07-29 19:36:58.052770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea7ae9a6049'
down_revision: Union[str, None] = 'fcd3bdb2b30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
